# License: GNU AGPLv3 (GNU Affero General Public License v3.0)
Feature: Edge Network Safety Guardrails and Outage Circuit Breakers

  Scenario: Blocking intrusive bandwidth tests during instructional hours
    Given the current time is 09:15 on a Monday (within instructional hours 07:30-16:30)
    And the emergency override flag is not set
    When the safety guardrails engine evaluates an iPerf3 bandwidth test request
    Then the test must be blocked with reason "instructional_hours_lockout"
    And no network traffic is generated by the test

  Scenario: Allowing intrusive tests outside instructional hours
    Given the current time is 18:00 on a Wednesday (outside instructional hours)
    When the safety guardrails engine evaluates an iPerf3 bandwidth test request
    Then the test is permitted to execute

  Scenario: Emergency override bypasses instructional hours lockout
    Given the current time is 10:00 on a Tuesday (within instructional hours)
    And the emergency override flag is set to true
    When the safety guardrails engine evaluates an iPerf3 bandwidth test request
    Then the test is permitted despite being within instructional hours

  Scenario: Pre-flight congestion check blocks test on high gateway latency
    Given the default gateway RTT is 35.0ms (above the 25.0ms threshold)
    When the pre-flight congestion check executes
    Then the bandwidth test must be blocked with reason "gateway_congested"
    And the measured gateway RTT is reported in the block reason

  Scenario: Thermal protection pauses tests above CPU temperature threshold
    Given the sensor SoC CPU temperature is 78.5°C (above the 75.0°C threshold)
    When the thermal safety check executes
    Then the test must be blocked with reason "thermal_protection"
    And testing resumes only when temperature drops below 65.0°C recovery threshold

  Scenario: Weekend and holiday bypass for off-peak testing
    Given the current time is 14:00 on a Saturday
    When the safety guardrails engine evaluates an iPerf3 bandwidth test request
    Then the test is permitted because weekends are not instructional hours
