#!/usr/bin/env python3
# License: GNU AGPLv3 (GNU Affero General Public License v3.0)
"""
High-Assurance Unit Test Suite for Multi-Resolver DNS Health & Benchmark Prober
Target: sensor/dns_multi_resolver_probe.py

Verifies:
  - Local resolver discovery and deduplication from /etc/resolv.conf
  - Fallback mechanism when resolv.conf is missing, empty, or unreadable
  - DNS query packet serialization (RFC 1035 UDP A-records)
  - DNS response header parsing and RCODE mappings
  - UDP probe execution: NOERROR success, NXDOMAIN, SERVFAIL, socket timeout, network error
  - Interface-bound socket configurations (SO_BINDTODEVICE)
  - Multi-resolver orchestration across local and public resolvers
  - Atomic Prometheus metrics emission and stdout fallback
  - CLI entrypoint argument handling
"""

import os
import sys
import socket
import tempfile
import unittest
from unittest.mock import patch, mock_open, MagicMock

# Ensure sensor directory is in sys.path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

def verifies(req_id: str):
    """Decorator to mark requirements traceability ID."""
    def decorator(fn):
        fn.__verifies__ = req_id
        return fn
    return decorator

import dns_multi_resolver_probe


class TestDnsMultiResolverProbe(unittest.TestCase):
    def setUp(self):
        self.test_dir = tempfile.TemporaryDirectory()
        self.prom_file = os.path.join(self.test_dir.name, "dns_resolvers.prom")

    def tearDown(self):
        self.test_dir.cleanup()

    # =========================================================================
    # 1. Local Resolver Discovery Tests
    # =========================================================================

    @verifies("REQ-PRB-010")
    def test_discover_local_resolvers_standard_and_deduplication(self):
        """Verifies parsing of nameservers with comments, other directives, and deduplication."""
        resolv_content = (
            "# Generated by NetworkManager\n"
            "search corp.example.com\n"
            "nameserver 10.100.1.1\n"
            "nameserver 10.100.1.2\n"
            "nameserver 10.100.1.1  # Duplicate entry\n"
            "options edns0 trust-ad\n"
            "nameserver 192.168.1.254\n"
        )
        with patch("os.path.exists", return_value=True), \
             patch("builtins.open", mock_open(read_data=resolv_content)):
            resolvers = dns_multi_resolver_probe.discover_local_resolvers()

        expected = [
            {"name": "Local-DNS (10.100.1.1)", "ip": "10.100.1.1", "is_public": False},
            {"name": "Local-DNS (10.100.1.2)", "ip": "10.100.1.2", "is_public": False},
            {"name": "Local-DNS (192.168.1.254)", "ip": "192.168.1.254", "is_public": False},
        ]
        self.assertEqual(resolvers, expected)

    @verifies("REQ-PRB-010")
    def test_discover_local_resolvers_file_not_found_fallback(self):
        """Verifies systemd-resolved fallback when /etc/resolv.conf does not exist."""
        with patch("os.path.exists", return_value=False):
            resolvers = dns_multi_resolver_probe.discover_local_resolvers()
        self.assertEqual(resolvers, [{"name": "System-Default", "ip": "127.0.0.53", "is_public": False}])

    @verifies("REQ-PRB-010")
    def test_discover_local_resolvers_empty_file_fallback(self):
        """Verifies fallback when /etc/resolv.conf exists but has no nameserver lines."""
        resolv_content = "# No active nameservers\nsearch localdomain\n"
        with patch("os.path.exists", return_value=True), \
             patch("builtins.open", mock_open(read_data=resolv_content)):
            resolvers = dns_multi_resolver_probe.discover_local_resolvers()
        self.assertEqual(resolvers, [{"name": "System-Default", "ip": "127.0.0.53", "is_public": False}])

    @verifies("REQ-PRB-010")
    def test_discover_local_resolvers_read_exception_fallback(self):
        """Verifies fallback when /etc/resolv.conf cannot be read due to OS/permission errors."""
        with patch("os.path.exists", return_value=True), \
             patch("builtins.open", side_effect=PermissionError("Access denied")):
            resolvers = dns_multi_resolver_probe.discover_local_resolvers()
        self.assertEqual(resolvers, [{"name": "System-Default", "ip": "127.0.0.53", "is_public": False}])

    # =========================================================================
    # 2. DNS Packet Construction & Parsing Tests
    # =========================================================================

    @verifies("REQ-PRB-010")
    def test_build_dns_query_packet_structure(self):
        """Verifies RFC 1035 UDP query serialization for domain labels and A record type."""
        domain = "google.com"
        with patch("random.randint", return_value=0x1234):
            packet = dns_multi_resolver_probe.build_dns_query(domain, query_type=1)

        # Header: TX_ID (0x1234), Flags (0x0100 - standard query, recursion desired), QDCOUNT (0x0001)
        expected_header = b"\x12\x34\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(packet[:12], expected_header)

        # Question: \x06 google \x03 com \x00 \x00\x01 (Type A) \x00\x01 (Class IN)
        expected_question = b"\x06google\x03com\x00\x00\x01\x00\x01"
        self.assertEqual(packet[12:], expected_question)

    @verifies("REQ-PRB-010")
    def test_parse_dns_response_rcodes(self):
        """Verifies RCODE extraction from response header flags."""
        # Short packet (< 4 bytes)
        rcode, rcode_str = dns_multi_resolver_probe.parse_dns_response(b"\x12\x34\x81")
        self.assertEqual(rcode, -1)
        self.assertEqual(rcode_str, "MALFORMED")

        # NOERROR (rcode = 0, standard response flags 0x8180)
        resp_noerror = b"\x12\x34\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_noerror), (0, "NOERROR"))

        # FORMERR (rcode = 1, flags 0x8181)
        resp_formerr = b"\x12\x34\x81\x81\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_formerr), (1, "FORMERR"))

        # SERVFAIL (rcode = 2, flags 0x8182)
        resp_servfail = b"\x12\x34\x81\x82\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_servfail), (2, "SERVFAIL"))

        # NXDOMAIN (rcode = 3, flags 0x8183)
        resp_nxdomain = b"\x12\x34\x81\x83\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_nxdomain), (3, "NXDOMAIN"))

        # NOTIMP (rcode = 4, flags 0x8184)
        resp_notimp = b"\x12\x34\x81\x84\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_notimp), (4, "NOTIMP"))

        # REFUSED (rcode = 5, flags 0x8185)
        resp_refused = b"\x12\x34\x81\x85\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_refused), (5, "REFUSED"))

        # Unmapped RCODE (e.g. 9)
        resp_other = b"\x12\x34\x81\x89\x00\x01\x00\x00\x00\x00\x00\x00"
        self.assertEqual(dns_multi_resolver_probe.parse_dns_response(resp_other), (9, "RCODE_9"))

    # =========================================================================
    # 3. DNS Server Probe Execution Tests
    # =========================================================================

    @verifies("REQ-PRB-010")
    @patch("socket.socket")
    def test_probe_dns_server_success(self, mock_socket_cls):
        """Verifies successful DNS resolution benchmark measuring positive latency and NOERROR."""
        mock_sock = MagicMock()
        mock_socket_cls.return_value = mock_sock
        resp_packet = b"\x12\x34\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00"
        mock_sock.recvfrom.return_value = (resp_packet, ("1.1.1.1", 53))

        with patch("time.time", side_effect=[100.000, 100.015]):
            result = dns_multi_resolver_probe.probe_dns_server("1.1.1.1", "google.com", timeout_sec=2.0)

        mock_sock.settimeout.assert_called_once_with(2.0)
        mock_sock.sendto.assert_called_once()
        mock_sock.close.assert_called_once()
        self.assertEqual(result["status"], 1)
        self.assertAlmostEqual(result["latency_seconds"], 0.015, places=3)
        self.assertEqual(result["rcode"], 0)
        self.assertEqual(result["rcode_str"], "NOERROR")

    @verifies("REQ-PRB-010")
    @patch("socket.socket")
    def test_probe_dns_server_nxdomain(self, mock_socket_cls):
        """Verifies probe result when domain does not exist (NXDOMAIN rcode=3, status=0)."""
        mock_sock = MagicMock()
        mock_socket_cls.return_value = mock_sock
        resp_packet = b"\x12\x34\x81\x83\x00\x01\x00\x00\x00\x00\x00\x00"
        mock_sock.recvfrom.return_value = (resp_packet, ("8.8.8.8", 53))

        with patch("time.time", side_effect=[100.0, 100.020]):
            result = dns_multi_resolver_probe.probe_dns_server("8.8.8.8", "nonexistent.k12.internal", timeout_sec=2.0)

        self.assertEqual(result["status"], 0)
        self.assertEqual(result["rcode"], 3)
        self.assertEqual(result["rcode_str"], "NXDOMAIN")
        mock_sock.close.assert_called_once()

    @verifies("REQ-PRB-010")
    @patch("socket.socket")
    def test_probe_dns_server_timeout(self, mock_socket_cls):
        """Verifies socket timeout handling when DNS server does not respond."""
        mock_sock = MagicMock()
        mock_socket_cls.return_value = mock_sock
        mock_sock.recvfrom.side_effect = socket.timeout("Timed out")

        result = dns_multi_resolver_probe.probe_dns_server("192.0.2.1", "google.com", timeout_sec=2.5)

        self.assertEqual(result["status"], 0)
        self.assertEqual(result["latency_seconds"], 2.5)
        self.assertEqual(result["rcode"], -1)
        self.assertEqual(result["rcode_str"], "TIMEOUT")
        mock_sock.close.assert_called_once()

    @verifies("REQ-PRB-010")
    @patch("socket.socket")
    def test_probe_dns_server_network_error(self, mock_socket_cls):
        """Verifies generic network exception handling during DNS resolution."""
        mock_sock = MagicMock()
        mock_socket_cls.return_value = mock_sock
        mock_sock.sendto.side_effect = OSError("Network unreachable")

        with patch("time.time", side_effect=[100.0, 100.005]):
            result = dns_multi_resolver_probe.probe_dns_server("10.0.0.1", "google.com", timeout_sec=2.0)

        self.assertEqual(result["status"], 0)
        self.assertEqual(result["rcode"], -2)
        self.assertIn("ERROR_Network unreachable", result["rcode_str"])
        mock_sock.close.assert_called_once()

    @verifies("REQ-PRB-010")
    @patch("socket.socket")
    def test_probe_dns_server_with_interface_binding(self, mock_socket_cls):
        """Verifies SO_BINDTODEVICE configuration when interface option is specified."""
        mock_sock = MagicMock()
        mock_socket_cls.return_value = mock_sock
        resp_packet = b"\x12\x34\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00"
        mock_sock.recvfrom.return_value = (resp_packet, ("1.1.1.1", 53))

        with patch.object(socket, "SO_BINDTODEVICE", 25, create=True), \
             patch("time.time", side_effect=[100.0, 100.010]):
            result = dns_multi_resolver_probe.probe_dns_server(
                "1.1.1.1", "google.com", timeout_sec=2.0, interface="eth0"
            )

        mock_sock.setsockopt.assert_called_once_with(socket.SOL_SOCKET, 25, b"eth0")
        self.assertEqual(result["status"], 1)

    @verifies("REQ-PRB-010")
    @patch("socket.socket")
    def test_probe_dns_server_interface_binding_exception_ignored(self, mock_socket_cls):
        """Verifies graceful continuation when setsockopt fails (e.g. non-root SO_BINDTODEVICE)."""
        mock_sock = MagicMock()
        mock_socket_cls.return_value = mock_sock
        mock_sock.setsockopt.side_effect = PermissionError("Operation not permitted")
        resp_packet = b"\x12\x34\x81\x80\x00\x01\x00\x01\x00\x00\x00\x00"
        mock_sock.recvfrom.return_value = (resp_packet, ("1.1.1.1", 53))

        with patch.object(socket, "SO_BINDTODEVICE", 25, create=True), \
             patch("time.time", side_effect=[100.0, 100.010]):
            result = dns_multi_resolver_probe.probe_dns_server(
                "1.1.1.1", "google.com", timeout_sec=2.0, interface="wlan0"
            )

        self.assertEqual(result["status"], 1)

    # =========================================================================
    # 4. Multi-Resolver Orchestration & Metrics Emission Tests
    # =========================================================================

    @verifies("REQ-PRB-010")
    @patch("dns_multi_resolver_probe.probe_dns_server")
    @patch("dns_multi_resolver_probe.discover_local_resolvers")
    def test_run_multi_resolver_probes(self, mock_discover, mock_probe):
        """Verifies orchestration across both discovered local resolvers and public resolvers."""
        mock_discover.return_value = [
            {"name": "Local-DNS (10.0.0.1)", "ip": "10.0.0.1", "is_public": False}
        ]
        mock_probe.return_value = {
            "status": 1,
            "latency_seconds": 0.012,
            "rcode": 0,
            "rcode_str": "NOERROR"
        }

        results = dns_multi_resolver_probe.run_multi_resolver_probes(interface="eth0")

        # 1 local + 4 public = 5 resolvers, 4 domains each = 20 probe executions
        total_resolvers = 1 + len(dns_multi_resolver_probe.PUBLIC_DNS_PROVIDERS)
        total_domains = len(dns_multi_resolver_probe.DEFAULT_BENCHMARK_DOMAINS)
        self.assertEqual(len(results), total_resolvers * total_domains)

        self.assertEqual(mock_probe.call_count, 20)
        # Check structure of first result
        first = results[0]
        self.assertEqual(first["resolver_name"], "Local-DNS (10.0.0.1)")
        self.assertEqual(first["resolver_ip"], "10.0.0.1")
        self.assertEqual(first["is_public"], 0)
        self.assertEqual(first["domain"], dns_multi_resolver_probe.DEFAULT_BENCHMARK_DOMAINS[0]["domain"])
        self.assertEqual(first["status"], 1)

    @verifies("REQ-PRB-010")
    def test_write_metrics_atomic_file_emission(self):
        """Verifies atomic write of Prometheus metrics with correct labels and formats."""
        sample_results = [
            {
                "resolver_name": "Local-DNS (10.0.0.1)",
                "resolver_ip": "10.0.0.1",
                "is_public": 0,
                "domain": "google.com",
                "status": 1,
                "latency_seconds": 0.0123,
                "rcode": 0,
                "rcode_str": "NOERROR"
            },
            {
                "resolver_name": "Cloudflare-Primary",
                "resolver_ip": "1.1.1.1",
                "is_public": 1,
                "domain": "canvas.net",
                "status": 0,
                "latency_seconds": 2.0,
                "rcode": -1,
                "rcode_str": "TIMEOUT"
            }
        ]

        dns_multi_resolver_probe.write_metrics(sample_results, self.prom_file)

        self.assertTrue(os.path.exists(self.prom_file))
        with open(self.prom_file, "r") as f:
            content = f.read()

        self.assertIn("# HELP openux_dns_resolver_status", content)
        self.assertIn("# TYPE openux_dns_resolver_status gauge", content)
        self.assertIn("# HELP openux_dns_resolver_latency_seconds", content)
        self.assertIn("# HELP openux_dns_resolver_rcode", content)

        self.assertIn('openux_dns_resolver_status{resolver="Local-DNS (10.0.0.1)",ip="10.0.0.1",domain="google.com",public="0"} 1', content)
        self.assertIn('openux_dns_resolver_latency_seconds{resolver="Local-DNS (10.0.0.1)",ip="10.0.0.1",domain="google.com",public="0"} 0.0123', content)
        self.assertIn('openux_dns_resolver_rcode{resolver="Local-DNS (10.0.0.1)",ip="10.0.0.1",domain="google.com",public="0"} 0', content)

        self.assertIn('openux_dns_resolver_status{resolver="Cloudflare-Primary",ip="1.1.1.1",domain="canvas.net",public="1"} 0', content)
        self.assertIn('openux_dns_resolver_latency_seconds{resolver="Cloudflare-Primary",ip="1.1.1.1",domain="canvas.net",public="1"} 2.0000', content)
        self.assertIn('openux_dns_resolver_rcode{resolver="Cloudflare-Primary",ip="1.1.1.1",domain="canvas.net",public="1"} -1', content)

    @verifies("REQ-PRB-010")
    def test_write_metrics_stdout_fallback(self):
        """Verifies stdout printing when output_path is empty."""
        sample_results = [
            {
                "resolver_name": "Google-Primary",
                "resolver_ip": "8.8.8.8",
                "is_public": 1,
                "domain": "google.com",
                "status": 1,
                "latency_seconds": 0.008,
                "rcode": 0,
                "rcode_str": "NOERROR"
            }
        ]
        with patch("builtins.print") as mock_print:
            dns_multi_resolver_probe.write_metrics(sample_results, output_path="")
            mock_print.assert_called()
            # Verify one of the print calls contains the metric line
            printed_outputs = [call.args[0] for call in mock_print.call_args_list if call.args]
            self.assertTrue(any("openux_dns_resolver_status" in str(out) for out in printed_outputs))

    # =========================================================================
    # 5. CLI Entrypoint Tests
    # =========================================================================

    @verifies("REQ-PRB-010")
    @patch("dns_multi_resolver_probe.write_metrics")
    @patch("dns_multi_resolver_probe.run_multi_resolver_probes")
    def test_cli_main(self, mock_run, mock_write):
        """Verifies CLI argument parsing and dispatching to probe runner and metric writer."""
        mock_run.return_value = [{"sample": 1}]
        test_args = ["dns_multi_resolver_probe.py", "--interface", "wlan0", "--output", self.prom_file]

        with patch.object(sys, "argv", test_args):
            dns_multi_resolver_probe.main()

        mock_run.assert_called_once_with(interface="wlan0")
        mock_write.assert_called_once_with([{"sample": 1}], self.prom_file)


if __name__ == "__main__":
    unittest.main()
